### ISSUE TITLE
Running latest example doesn't work with TS 2.7.2

### ISSUE THREAD

**Issue by henrikra** [yayoc/optional-chain#3]
When running following code with TS 2.7.2

```typescript
type User = {
  name?: {
    first: string
  }
}
const user: User = {name: null};
const optionalUser = optional(user);
optionalUser.k("name").k("first").get();
```

I will get error `Property 'get' does not exist on type 'Option<string>'`

![image](https://user-images.githubusercontent.com/12229968/42995537-ccbcfb4a-8c19-11e8-8150-d5db1c0abc1f.png)

What is wrong? With TS 2.9.2 I will not get error. Problem is that I am not able to upgrade TS yet because of other problems

**Comment by henrikra** [comment]
Hmm I guess it is because of this line: https://github.com/yayoc/optional-chain/blob/master/src/index.ts#L10
Since conditional types came to TS in 2.8 :/

**Comment by yayoc** [comment]
Yes, This library requires TS 2.8+ to use conditional types.

**Comment by henrikra** [comment]
Maybe you should add it to README?

**Comment by yayoc** [comment]
I noted the requirement on README, Thanks.

**Comment by henrikra** [comment]
Very nice! I am able to test this in couple weeks since then I can update to TS 2.8. Have you used this library in production yet or just hobby projects?
